// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// charlie_dma //
// ----------- //

#define charlie_dma_wrap_target 0
#define charlie_dma_wrap 10
#define charlie_dma_pio_version 1

static const uint16_t charlie_dma_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6048, //  1: out    y, 8
    0xa062, //  2: mov    pindirs, y
    0x0067, //  3: jmp    !y, 7
    0x6008, //  4: out    pins, 8
    0x6030, //  5: out    x, 16
    0x0009, //  6: jmp    9
    0xa003, //  7: mov    pins, null
    0xa027, //  8: mov    x, osr
    0x0049, //  9: jmp    x--, 9
    0xe000, // 10: set    pins, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program charlie_dma_program = {
    .instructions = charlie_dma_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = charlie_dma_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config charlie_dma_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + charlie_dma_wrap_target, offset + charlie_dma_wrap);
    return c;
}

static inline void charlie_dma_program_init(PIO pio, uint sm, uint offset, uint first_pin, uint pin_count) {
    pio_sm_config c = charlie_dma_program_get_default_config(offset);
    sm_config_set_out_pins(&c, first_pin, pin_count);
    sm_config_set_set_pins(&c, first_pin, pin_count);
    // Ensure we are shifting RIGHT and autopull is OFF (we use 'pull block')
    sm_config_set_out_shift(&c, true, false, 32);
    for(int i=0; i<pin_count; i++) {
        uint pin = first_pin + i;
        pio_gpio_init(pio, pin%32);
        gpio_set_drive_strength(pin%32, GPIO_DRIVE_STRENGTH_12MA);
    }
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

