// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// logic_analyzer //
// -------------- //

#define logic_analyzer_wrap_target 1
#define logic_analyzer_wrap 15
#define logic_analyzer_pio_version 0

static const uint16_t logic_analyzer_program_instructions[] = {
    0xa020, //  0: mov    x, pins
            //     .wrap_target
    0xa0eb, //  1: mov    osr, ~null
    0x60d5, //  2: out    isr, 21
    0xa040, //  3: mov    y, pins
    0x00ab, //  4: jmp    x != y, 11
    0xa046, //  5: mov    y, isr
    0x0089, //  6: jmp    y--, 9
    0xa041, //  7: mov    y, x
    0x000b, //  8: jmp    11
    0xa0c2, //  9: mov    isr, y
    0x0003, // 10: jmp    3
    0xa0e6, // 11: mov    osr, isr
    0x404b, // 12: in     y, 11
    0x40f5, // 13: in     osr, 21
    0x8000, // 14: push   noblock
    0xa022, // 15: mov    x, y
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program logic_analyzer_program = {
    .instructions = logic_analyzer_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = logic_analyzer_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config logic_analyzer_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + logic_analyzer_wrap_target, offset + logic_analyzer_wrap);
    return c;
}
#endif

