// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// set_pins //
// -------- //

#define set_pins_wrap_target 0
#define set_pins_wrap 11
#define set_pins_pio_version 1

static const uint16_t set_pins_program_instructions[] = {
            //     .wrap_target
    0xe029, //  0: set    x, 9
    0xa061, //  1: mov    pindirs, x
    0xe028, //  2: set    x, 8
    0xbf01, //  3: mov    pins, x                [31]
    0xe020, //  4: set    x, 0
    0xbf01, //  5: mov    pins, x                [31]
    0xe021, //  6: set    x, 1
    0xbf01, //  7: mov    pins, x                [31]
    0xe020, //  8: set    x, 0
    0xbf01, //  9: mov    pins, x                [31]
    0xa061, // 10: mov    pindirs, x
    0x0000, // 11: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program set_pins_program = {
    .instructions = set_pins_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = set_pins_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config set_pins_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + set_pins_wrap_target, offset + set_pins_wrap);
    return c;
}
#endif

