// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// charlie_dma //
// ----------- //

#define charlie_dma_wrap_target 0
#define charlie_dma_wrap 10
#define charlie_dma_pio_version 1

static const uint16_t charlie_dma_program_instructions[] = {
            //     .wrap_target
    0xa003, //  0: mov    pins, null
    0x80a0, //  1: pull   block
    0x6028, //  2: out    x, 8
    0x0029, //  3: jmp    !x, 9
    0x6088, //  4: out    pindirs, 8
    0x6050, //  5: out    y, 16
    0x0060, //  6: jmp    !y, 0
    0xa001, //  7: mov    pins, x
    0x000a, //  8: jmp    10
    0x6058, //  9: out    y, 24
    0x008a, // 10: jmp    y--, 10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program charlie_dma_program = {
    .instructions = charlie_dma_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = charlie_dma_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config charlie_dma_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + charlie_dma_wrap_target, offset + charlie_dma_wrap);
    return c;
}

static inline void charlie_dma_program_init(PIO pio, uint sm, uint offset, uint first_pin, uint pin_count) {
    pio_sm_config c = charlie_dma_program_get_default_config(offset);
    sm_config_set_out_pins(&c, first_pin, pin_count);
    //sm_config_set_set_pins(&c, first_pin, pin_count); //disable to get GP0 to work right (WAS open-drain, IS push-pull)
    // Ensure we are shifting RIGHT and autopull is OFF (we use 'pull block')
    sm_config_set_out_shift(&c, true, false, 32);
    for(int i=0; i<pin_count; i++) {
        uint pin = (first_pin + i) % 32;
        pio_gpio_init(pio, pin);
        gpio_set_drive_strength(pin, GPIO_DRIVE_STRENGTH_12MA);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, first_pin, pin_count, true); //needed to get GP0 to work right (WAS open-drain, IS push-pull)
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

