// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// pio_adder //
// --------- //

#define pio_adder_wrap_target 0
#define pio_adder_wrap 8

static const uint16_t pio_adder_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xa02f, //  1: mov    x, !osr                    
    0x80a0, //  2: pull   block                      
    0xa047, //  3: mov    y, osr                     
    0x0086, //  4: jmp    y--, 6                     
    0x0007, //  5: jmp    7                          
    0x0044, //  6: jmp    x--, 4                     
    0xa0c9, //  7: mov    isr, !x                    
    0x8020, //  8: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_adder_program = {
    .instructions = pio_adder_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config pio_adder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_adder_wrap_target, offset + pio_adder_wrap);
    return c;
}
#endif
