// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// logic_analyzer //
// -------------- //

#define logic_analyzer_wrap_target 1
#define logic_analyzer_wrap 14
#define logic_analyzer_pio_version 0

static const uint16_t logic_analyzer_program_instructions[] = {
    0xa020, //  0: mov    x, pins
            //     .wrap_target
    0xa0eb, //  1: mov    osr, ~null
    0x60d5, //  2: out    isr, 21
    0x606b, //  3: out    null, 11
    0xa040, //  4: mov    y, pins
    0x00ac, //  5: jmp    x != y, 12
    0xa046, //  6: mov    y, isr
    0x008a, //  7: jmp    y--, 10
    0xa041, //  8: mov    y, x
    0x000c, //  9: jmp    12
    0xa0c2, // 10: mov    isr, y
    0x0004, // 11: jmp    4
    0x404b, // 12: in     y, 11
    0x8000, // 13: push   noblock
    0xa022, // 14: mov    x, y
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program logic_analyzer_program = {
    .instructions = logic_analyzer_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = logic_analyzer_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config logic_analyzer_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + logic_analyzer_wrap_target, offset + logic_analyzer_wrap);
    return c;
}
#endif

