// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// charlie_dma //
// ----------- //

#define charlie_dma_wrap_target 0
#define charlie_dma_wrap 4
#define charlie_dma_pio_version 0

static const uint16_t charlie_dma_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6088, //  1: out    pindirs, 8
    0x6008, //  2: out    pins, 8
    0x6030, //  3: out    x, 16
    0x0044, //  4: jmp    x--, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program charlie_dma_program = {
    .instructions = charlie_dma_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = charlie_dma_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config charlie_dma_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + charlie_dma_wrap_target, offset + charlie_dma_wrap);
    return c;
}

static inline void charlie_dma_program_init(PIO pio, uint sm, uint offset, uint first_pin, uint pin_count) {
    pio_sm_config c = charlie_dma_program_get_default_config(offset);
    // Set 'out' pins to start at first_pin for pin_count number of pins
    sm_config_set_out_pins(&c, first_pin, pin_count);
    // Set 'pindirs' to affect the same pins
    // Note: pio_sm_set_pindirs is usually handled via the out instruction
    // Connect GPIOs to the PIO block
    for(int i=0; i<pin_count; i++) {
        pio_gpio_init(pio, first_pin + i);
    }
    // Load configuration and start
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

