// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// led //
// --- //

#define led_wrap_target 0
#define led_wrap 10
#define led_pio_version 1

static const uint16_t led_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6028, //  1: out    x, 8
    0x0027, //  2: jmp    !x, 7
    0xa061, //  3: mov    pindirs, x
    0x6008, //  4: out    pins, 8
    0x6050, //  5: out    y, 16
    0x000a, //  6: jmp    10
    0xa063, //  7: mov    pindirs, null
    0xa003, //  8: mov    pins, null
    0x6058, //  9: out    y, 24
    0x008a, // 10: jmp    y--, 10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program led_program = {
    .instructions = led_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = led_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config led_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + led_wrap_target, offset + led_wrap);
    return c;
}
#endif

