#include "hardware/pio.h"
#include "hardware/dma.h"
#include "led.pio.h"

// Include your autogenerated PIO header contents directly
/*#define led_wrap_target 0
#define led_wrap 10
#define led_pio_version 1*/

/*static const uint16_t led_program_instructions[] = {
    0x80a0, 0x6028, 0x0027, 0xa061, 0x6008, 0x6050, 0x000a, 0xa063, 0xa003, 0x6058, 0x008a
};

static const struct pio_program led_program = {
    .instructions = led_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = led_pio_version,
};*/

// Base definitions
const uint8_t CHARLIPLEX_LED_COUNT = 48;
const uint8_t TOTAL_ELEMENTS = 49; // 48 LEDs + 1 Wait state

// Pin configurations
const uint8_t LOWER_BASE_PIN = 0;  // GP0-GP7
const uint8_t UPPER_BASE_PIN = 16; // GP16-GP23

// Input config matrices
uint16_t const CHARLIEPLEX_PINOUT_CONFIG[2][CHARLIPLEX_LED_COUNT]={//index 0: lower LEDs config (under screen), index 1: upper LEDs (in hair)
{//lower LEDs
//red [0..23] left-to-right from led_matrix.ods.  MSB is pin (1=high, 0=low), LSB is dir (output=1, float=0)
0x4060,0x4048,0x020A,0x0222,0x0282,0x0242,0x0109,0x0121,0x0141,0x0111,0x0103,0x0181,0x2060,0x0848,0x080A,0x2022,0x4042,0x8082,0x8081,0x4041,0x2021,0x0809,0x1011,0x0203,

//green 24..47 left-to-right
0x80A0,0x8088,0x1018,0x1030,0x1090,0x1050,0x040C,0x0424,0x0444,0x0414,0x0406,0x0484,0x20A0,0x0888,0x0818,0x2030,0x4050,0x8090,0x8084,0x4044,0x2024,0x080C,0x1014,0x0206
},{//upper LEDs
//red CW around her face, then mostly left-to-right (and bottom-to-top along diagonals)
0x0103,0x0111,0x8082,0x8090,0x8081,0x80A0,0x0406,0x0414,0x0405,0x0424,0x0444,0x0484,0x0203,0x1011,0x0282,0x1090,0x0181,0x20A0,0x0206,0x1014,0x0105,0x2024,0x4044,0x8084,

//green
0x2022,0x2030,0x4042,0x4050,0x4041,0x4060,0x080A,0x0818,0x0809,0x0828,0x0848,0x0888,0x0222,0x1030,0x0242,0x1050,0x0141,0x2060,0x020A,0x1018,0x0109,0x2028,0x4048,0x8088
}};

// 32-bit DMA buffers formatted for PIO processing
// PIO shifts out: 8 bits pindirs (MSB) -> 8 bits pins -> 16 bits delay (LSB)
uint32_t lower_dma_buffer[TOTAL_ELEMENTS];
uint32_t upper_dma_buffer[TOTAL_ELEMENTS];

// Pointers for Control Blocks to implement reset chains
uint32_t* lower_reset_ptr = &lower_dma_buffer[0];
uint32_t* upper_reset_ptr = &upper_dma_buffer[0];

// Global DMA channels allocations
int dma_l1, dma_l2;
int dma_u1, dma_u2;

void setup() {
    //delay(2000);
    // 1. Set pins GP0-7 and GP16-23 to INPUT to clear weak pull-ups/pull-downs
    for (int i = 0; i < 8; i++) {
        pinMode(LOWER_BASE_PIN + i, INPUT);
        pinMode(UPPER_BASE_PIN + i, INPUT);
    }

    // 2. Format configuration data into 32-bit structures for PIO engine
    // Pack scheme: [ pindirs (8-bit) | pins (8-bit) | loop_delay (16-bit) ]
    uint16_t delay_ticks = 2000; // Adjust for LED scan-line display time
    
    for (int i = 0; i < CHARLIPLEX_LED_COUNT; i++) {
        lower_dma_buffer[i] = ((uint32_t)delay_ticks << 16) | CHARLIEPLEX_PINOUT_CONFIG[0][i];
        upper_dma_buffer[i] = ((uint32_t)delay_ticks << 16) | CHARLIEPLEX_PINOUT_CONFIG[1][i];
    }

    // Element 49: Terminal synchronization step (Pindirs=0, Pins=0, loops for blank frame step)
    lower_dma_buffer[TOTAL_ELEMENTS - 1] = 0x000001UL << 8;
    upper_dma_buffer[TOTAL_ELEMENTS - 1] = 0x000001UL << 8;

    // 3. PIO System Initialization
    PIO pio = pio0; // Using PIO instance 0
    uint offset = pio_add_program(pio, &led_program);

    // Claim state machines
    int sm_lower = pio_claim_unused_sm(pio, true);
    int sm_upper = pio_claim_unused_sm(pio, true);

    // Configure Lower Bank State Machine (GP0-7)
    pio_sm_config c_lower = pio_get_default_sm_config();
    sm_config_set_wrap(&c_lower, offset + led_wrap_target, offset + led_wrap);
    sm_config_set_out_pins(&c_lower, LOWER_BASE_PIN, 8);
    //sm_config_set_set_pins(&c_lower, LOWER_BASE_PIN, 8);
    // Shift right, autopull enabled, threshold = 32 bits
    sm_config_set_out_shift(&c_lower, true, false, 32); 
    pio_sm_set_consecutive_pindirs(pio, sm_lower, LOWER_BASE_PIN, 8, true);
    
    // Configure pins inside PIO framework
    for(int i=0; i<8; i++) {
        pio_gpio_init(pio, LOWER_BASE_PIN + i);
    }
    pio_sm_init(pio, sm_lower, offset, &c_lower);

    // Configure Upper Bank State Machine (GP16-23)
    pio_sm_config c_upper = pio_get_default_sm_config();
    sm_config_set_wrap(&c_upper, offset + led_wrap_target, offset + led_wrap);
    sm_config_set_out_pins(&c_upper, UPPER_BASE_PIN, 8);
    //sm_config_set_set_pins(&c_upper, UPPER_BASE_PIN, 8);
    sm_config_set_out_shift(&c_upper, true, false, 32);
    pio_sm_set_consecutive_pindirs(pio, sm_upper, UPPER_BASE_PIN, 8, true);

    for(int i=0; i<8; i++) {
        pio_gpio_init(pio, UPPER_BASE_PIN + i);
    }
    pio_sm_init(pio, sm_upper, offset, &c_upper);

    // Start execution on both State Machines
    pio_sm_set_enabled(pio, sm_lower, true);
    pio_sm_set_enabled(pio, sm_upper, true);

    // 4. DMA Configuration & Circular Loop Setup
    dma_l1 = dma_claim_unused_channel(true); // Lower Data Engine
    dma_l2 = dma_claim_unused_channel(true); // Lower Reset Control Trigger
    dma_u1 = dma_claim_unused_channel(true); // Upper Data Engine
    dma_u2 = dma_claim_unused_channel(true); // Upper Reset Control Trigger

    // --- Lower Engine Setup ---
    dma_channel_config cl1 = dma_channel_get_default_config(dma_l1);
    channel_config_set_transfer_data_size(&cl1, DMA_SIZE_32);
    channel_config_set_read_increment(&cl1, true);
    channel_config_set_write_increment(&cl1, false);
    channel_config_set_dreq(&cl1, pio_get_dreq(pio, sm_lower, true));
    channel_config_set_chain_to(&cl1, dma_l2); // Trigger L2 reset when L1 array completes

    dma_channel_configure(dma_l1, &cl1,
        &pio->txf[sm_lower], // Write destination
        lower_dma_buffer,    // Read source
        TOTAL_ELEMENTS,      // Element count
        false                // Do not start yet
    );

    dma_channel_config cl2 = dma_channel_get_default_config(dma_l2);
    channel_config_set_transfer_data_size(&cl2, DMA_SIZE_32);
    channel_config_set_read_increment(&cl2, false); // Keep reading the exact same pointer address
    channel_config_set_write_increment(&cl2, false);

    // Pass the actual pointer variable address instead of an indirect reference address
    dma_channel_configure(dma_l2, &cl2,
        &dma_hw->ch[dma_l1].al3_read_addr_trig, // CRITICAL: Target the trigger alias register to re-arm L1
        &lower_reset_ptr,                       // Source is the pointer variable containing &lower_dma_buffer[0]
        1,                                      // Single 32-bit transfer execution
        false                                   // Do not start yet
    );

    // --- Upper Engine Setup ---
    dma_channel_config cu1 = dma_channel_get_default_config(dma_u1);
    channel_config_set_transfer_data_size(&cu1, DMA_SIZE_32);
    channel_config_set_read_increment(&cu1, true);
    channel_config_set_write_increment(&cu1, false);
    channel_config_set_dreq(&cu1, pio_get_dreq(pio, sm_upper, true));
    channel_config_set_chain_to(&cu1, dma_u2); // Trigger U2 reset when U1 array completes

    dma_channel_configure(dma_u1, &cu1,
        &pio->txf[sm_upper], // Write destination
        upper_dma_buffer,    // Read source
        TOTAL_ELEMENTS,      // Element count
        false                // Do not start yet
    );

    dma_channel_config cu2 = dma_channel_get_default_config(dma_u2);
    channel_config_set_transfer_data_size(&cu2, DMA_SIZE_32);
    channel_config_set_read_increment(&cu2, false); 
    channel_config_set_write_increment(&cu2, false);

    dma_channel_configure(dma_u2, &cu2,
        &dma_hw->ch[dma_u1].al3_read_addr_trig, // CRITICAL: Target the trigger alias register to re-arm U1
        &upper_reset_ptr,                       // Source is the pointer variable containing &upper_dma_buffer[0]
        1,                                      // Single 32-bit transfer execution
        false                                   // Do not start yet
    );

    // Fire up both loop engines concurrently
    dma_channel_start(dma_l1);
    dma_channel_start(dma_u1);
}

void loop() {
    // Zero CPU overhead. Loops continue to handle frame outputs automatically via hardware DMA.
}
