// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// set_pins //
// -------- //

#define set_pins_wrap_target 0
#define set_pins_wrap 2
#define set_pins_pio_version 0

static const uint16_t set_pins_program_instructions[] = {
            //     .wrap_target
    0xe089, //  0: set    pindirs, 9
    0xe001, //  1: set    pins, 1
    0x0002, //  2: jmp    2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program set_pins_program = {
    .instructions = set_pins_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = set_pins_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config set_pins_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + set_pins_wrap_target, offset + set_pins_wrap);
    return c;
}
#endif

