// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// button_scanner //
// -------------- //

#define button_scanner_wrap_target 0
#define button_scanner_wrap 12
#define button_scanner_pio_version 1

#define button_scanner_DELAY_BIT_COUNT 1

static const uint16_t button_scanner_program_instructions[] = {
            //     .wrap_target
    0xa00b, //  0: mov    pins, ~null
    0xa06b, //  1: mov    pindirs, ~null
    0xa063, //  2: mov    pindirs, null
    0xa02b, //  3: mov    x, ~null
    0xa0c3, //  4: mov    isr, null
    0x4029, //  5: in     x, 9
    0xa026, //  6: mov    x, isr
    0x0047, //  7: jmp    x--, 7
    0x4010, //  8: in     pins, 16
    0x8000, //  9: push   noblock
    0xa020, // 10: mov    x, pins
    0x0020, // 11: jmp    !x, 0
    0x000a, // 12: jmp    10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program button_scanner_program = {
    .instructions = button_scanner_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = button_scanner_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config button_scanner_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + button_scanner_wrap_target, offset + button_scanner_wrap);
    return c;
}
#endif

